version: 2
updates:

  - package-ecosystem: "pip" 
    directory: "/01-Authoirzation" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
