version: 2
jobs:
  build:
    working_directory: ~/repo/01-Authorization
    machine:
      image: ubuntu-2004:202107-02
           
    steps:
      - checkout:
         path: ~/repo

      - run: 
          name: Set .env file
          command: |
              echo "AUTH0_DOMAIN=$auth0_domain" >> .env
              echo "API_IDENTIFIER=$api_identifier" >> .env
 
      - run: 
           name: background server
           command: sh exec.sh
           background: true
           
      - run:
           name: Wait until server is online
           command: |
              until $(curl --output /dev/null --silent --fail http://localhost:3010/api/public); do
                  sleep 5
              done
         
      - run:
          name: Clone script test
          command: git clone -b v0.0.1 --depth 1 https://github.com/auth0-samples/api-quickstarts-tests test
                      
      - run: 
          name: Prepare environment variables for test
          command: |
            cd test
            echo "AUTH0_DOMAIN=$auth0_domain" >> .env
            echo "API_IDENTIFIER=$api_identifier" >> .env
            echo "AUTH0_CLIENT_ID_1=$client_id_scopes_none" >> .env
            echo "AUTH0_CLIENT_SECRET_1=$client_secret_scopes_none" >> .env
            echo "AUTH0_CLIENT_ID_2=$client_id_scopes_read" >> .env
            echo "AUTH0_CLIENT_SECRET_2=$client_secret_scopes_read" >> .env
            echo "AUTH0_CLIENT_ID_3=$client_id_scopes_write" >> .env
            echo "AUTH0_CLIENT_SECRET_3=$client_secret_scopes_write" >> .env
            echo "AUTH0_CLIENT_ID_4=$client_id_scopes_readwrite" >> .env
            echo "AUTH0_CLIENT_SECRET_4=$client_secret_scopes_readwrite" >> .env
            echo "API_URL=http://localhost:3010" >> .env

      - run:
          name: Install test script dependency
          command: cd test && npm install

      - run:
          name: Test
          command: cd test && npm test
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Quickstart API Tests

